version: '3.8'
services:
  backend:
    container_name: hotels_backend
    restart: always
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - go_modules:/go/pkg/mod
      - public:/api/static
      - image_files:/api/static/images/hotels
    networks:
      - app-network

  frontend:
    container_name: hotels_frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
    networks:
      - app-network

  db:
    image: mysql
    container_name: hotels_mysql
    restart: always
    environment:
      MYSQL_DATABASE: hotels_booking
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  go_modules:
  node_modules:
  image_files:
  public:
