version: "3.8"
services:
  backend:
    container_name: hotels_backend
    restart: always
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - go_modules:/go/pkg/mod

  frontend:
    container_name: hotels_frontend
    links:
      - backend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules

  db:
    image: mysql
    container_name: hotels_mysql
    restart: always
    environment:
      MYSQL_DATABASE: hotels_booking
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  go_modules:
  node_modules:
